tuto_doctrine_person_index:
    path:     /
    defaults: { _controller: "TutoDoctrineTutoBundle:Person:index" }
    methods:  GET

tuto_doctrine_person_show:
    path:     /{id}/show
    defaults: { _controller: "TutoDoctrineTutoBundle:Person:show" }
    methods:  GET

tuto_doctrine_person_new:
    path:     /new
    defaults: { _controller: "TutoDoctrineTutoBundle:Person:new" }
    methods:  [GET, POST]

tuto_doctrine_person_edit:
    path:     /{id}/edit
    defaults: { _controller: "TutoDoctrineTutoBundle:Person:edit" }
    methods:  [GET, POST]

tuto_doctrine_person_delete:
    path:     /{id}/delete
    defaults: { _controller: "TutoDoctrineTutoBundle:Person:delete" }
    methods:  DELETE
