services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }